# 集群设置
cluster.name: elasticsearch-cluster
node.name: es-node-1

# 路径设置
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# 网络设置
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# 发现设置
discovery.type: single-node

# 安全设置 (开发环境)
xpack.security.enabled: false
xpack.ml.enabled: false

# 索引设置
action.auto_create_index: "+*"

# 跨域设置
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "Authorization,X-Requested-With,Content-Length,Content-Type"

# 性能优化
indices.query.bool.max_clause_count: 2048
thread_pool.search.queue_size: 1000
